### PR TITLE
Make bootstrap nodes configurable.

### PR DESCRIPTION
**Pull request by yanzay**
Would be great if we can use custom bootstrap nodes, not public.

### CODE REVIEW

**Comment by digitalcrab** [comment]
@miolini , your opinion? I think that's cool feature!

**Comment by miolini** [comment]
@yanzay SGTM. But merge conflicts first.

**Comment by miolini** [comment]
@gen1us2k how is it? )

**Comment by yanzay** [comment]
@miolini conflicts resolved, is it ok now?

**Comment by miolini** [comment]
@yanzay yes

**Pull request merged**
